doctrine:
  dbal:
    types:
      uuid:
        class: 'App\Doctrine\Type\Uuid'
        commented: true
    driver: 'pdo_pgsql'
    server_version: '11'
    charset: UTF8
    dbname:   '%env(resolve:POSTGRES_DB)%'
    host:     '%env(resolve:DATABASE_URL)%'
    port:     '%env(resolve:DATABASE_PORT)%'
    user:     '%env(resolve:POSTGRES_USER)%'
    password: '%env(resolve:POSTGRES_PASSWORD)%'
    schema_filter: '~^(?!messenger_messages)~' # Messenger component table
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App