version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/var/www/app:cached

  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data:cached
      - ./docker/dev/database:/docker-entrypoint-initdb.d
    env_file:
      - .env.local

  webapp:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    env_file:
      - .env.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/app:cached

volumes:
  database: {}
