version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/var/www/app:cached

  webapp:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    env_file:
      - .env.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/app:cached

volumes:
  database: {}
